{% set name = "qpytorch" %}
{% set version = "0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name|lower }}/qpytorch-{{ version }}.tar.gz
  sha256: 0f4096181286d69b0581e961e1a05ba2628119cd6ffdc19b2781bb254f9dabcc

build:
  noarch: python
  number: 0
  script:
    - rm -rf test
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.0
    - jaxtyping
    - mpmath >=0.19,<=1.3
    - scikit-learn
    - scipy >=1.6.0
    - linear_operator >=0.6
    - gpytorch >=1.13
    - numpy <2

test:
  imports:
    - qpytorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://lanzithinking.github.io/QePyTorch
  summary: An implementation of Q-Exponential Processes in Pytorch based on GPyTorch
  doc_url: https://pypi.org/project/qpytorch/
  dev_url: https://github.com/lanzithinking/qepytorch/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lanzithinking
